	<script src="{$ABS_PATH}lib/scripts/jquery-1.11.1.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/nprogress.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery-ui.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery-ui-time.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.form.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.transform.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.cookie.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.jgrowl.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.alerts.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.tipsy.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.totop.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.dataTables.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.collapsible.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.nicefileinput.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.placeholder.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.sticky.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.fancybox.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.autocomplete.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.formstyler.min.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/jquery.nestable.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/mousetrap.js" type="text/javascript"></script>
	<script src="{$ABS_PATH}lib/scripts/clipboard.min.js" type="text/javascript"></script>